---
apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
  - name: curl
    command: ["sleep", "3600"]
    image: harbor.kakor.ovh/public/curl:latest
    securityContext:
      allowPrivilegeEscalation: true